Shader "Hidden/DepthToMeters"
{
    SubShader
    {
        Tags { "RenderType" = "Opaque" }
        ZWrite Off
        ZTest Always
        Cull Off

        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include "UnityCG.cginc"

            // Standard fullscreen quad input for Blit
            struct appdata
            {
                float4 vertex : POSITION;
                float2 uv     : TEXCOORD0;
            };

            struct v2f
            {
                float4 pos       : SV_POSITION;
                float4 screenPos : TEXCOORD0;
            };

            // Depth texture generated by the camera
            UNITY_DECLARE_DEPTH_TEXTURE(_CameraDepthTexture);

            v2f vert(appdata v)
            {
                v2f o;
                o.pos = UnityObjectToClipPos(v.vertex);
                o.screenPos = ComputeScreenPos(o.pos);
                return o;
            }

            float4 frag(v2f i) : SV_Target
            {
                // Sample raw hardware depth (0..1, non-linear)
                float raw = SAMPLE_DEPTH_TEXTURE_PROJ(
                    _CameraDepthTexture,
                    UNITY_PROJ_COORD(i.screenPos)
                );

                // Convert to linear eye depth in world units (Unity units)
                // This uses _ZBufferParams under the hood
                float depthMeters = LinearEyeDepth(raw);

                // Write depth in meters into all channels
                return float4(depthMeters, depthMeters, depthMeters, 1.0);
            }
            ENDCG
        }
    }

    FallBack Off
}

